#  Copyright (c) 2026. Richard Vermillion. All Rights Reserved.

import time
from dataclasses import dataclass
from contextlib import contextmanager
from typing import Generator

from ..common import *
from ..nn import Module
from ..nn.cache import ModelCache
from .language import LanguageModel



@dataclass
class GenerationResponse:
    """
    The output of :func:`stream_generate`.

    Args:
        text (str): The next segment of decoded text. This can be an empty string.
        token (int): The next token.
        from_draft (bool): Whether the token was generated by the draft model.
        logprobs (Array): A vector of log probabilities.
        prompt_tokens (int): The number of tokens in the prompt.
        prompt_tps (float): The prompt processing tokens-per-second.
        generation_tokens (int): The number of generated tokens.
        generation_tps (float): The tokens-per-second for generation.
        peak_memory (float): The peak memory used so far in GB.
        finish_reason (str): The reason the response is being sent: "length", "stop" or `None`
    """

    text: str
    token: int
    logprobs: Array
    from_draft: bool
    prompt_tokens: int
    prompt_tps: float
    generation_tokens: int
    generation_tps: float
    peak_memory: float
    finish_reason: Optional[str] = None



@contextmanager
def wired_limit(model: Module, streams: Optional[list[ten.Stream]] = None):

    """
    A context manager to temporarily change the wired limit.

    Note, the wired limit should not be changed during an async eval.  If an
    async eval could be running pass in the streams to synchronize with prior
    to exiting the context manager.
    """
    model_bytes = tree.reduce(
        lambda acc, x: acc + x.nbytes if isinstance(x, Array) else acc, model,
        initializer=0,
    )
    max_rec_size = ten.device_info()["max_recommended_working_set_size"]
    if model_bytes > 0.9 * max_rec_size:
        model_mb = model_bytes // 2**20
        max_rec_mb = max_rec_size // 2**20
        print(
            f"[WARNING] Generating with a model that requires {model_mb} MB "
            f"which is close to the maximum recommended size of {max_rec_mb} "
            "MB. This can be slow. See the documentation for possible work-arounds: "
            "https://github.com/ml-explore/mlx-examples/tree/main/llms#large-models"
        )
    old_limit = ten.set_wired_limit(max_rec_size)
    try:
        yield None
    finally:
        if streams is not None:
            for s in streams:
                ten.synchronize(s)
        else:
            ten.synchronize()
        ten.set_wired_limit(old_limit)


class Detokenizer(Protocol):

    last_segment: str

    def decode(self, tokens: list[int], **kwargs) -> str: ...

    def add_token(self, token: int) -> None: ...

    def finalize(self) -> None: ...


class Tokenizer(Protocol):

    bos_token: str

    eos_token_ids: set[int]

    detokenizer: Detokenizer

    def encode(self, text: str, **kwargs) -> list[int]: ...


generation_stream = ten.new_stream(ten.default_device())


Sampler = Callable[[Array], Array]
LogitProcessor = Callable[[Array, Array], Array]


def greedy_sampler(x: Array) -> Array:
    return ten.argmax(x, axis=-1)


default_sampler: Sampler = greedy_sampler


def generate_step(
    prompt: Array,
    model: LanguageModel,
    *,
    max_tokens: int = 256,
    sampler: Optional[Sampler] = None,
    logits_processors: Optional[list[LogitProcessor]] = None,
    max_kv_size: Optional[int] = None,
    prompt_cache: Optional[ModelCache] = None,
    prefill_step_size: int = 2048,
    prompt_progress_callback: Optional[Callable[[int, int], None]] = None,
) -> Generator[tuple[int|float|bool, Array], None, None]:
    """
    A generator producing token ids based on the given prompt from the model.

    Args:
        prompt (Array): The input prompt.
        model (nn.Module): The model to use for generation.
        max_tokens (int): The maximum number of tokens. Use``-1`` for an infinite
          generator. Default: ``256``.
        sampler (Callable[Array, Array], optional): A sampler for sampling a
          token from a vector of log probabilities. Default: ``None``.
        logits_processors (List[Callable[[Array, Array], Array]], optional):
          A list of functions that take tokens and logits and return the processed
          logits. Default: ``None``.
        max_kv_size (int, optional): Maximum size of the key-value cache. Old
          entries (except the first 4 tokens) will be overwritten.
        prompt_cache (List[Any], optional): A pre-computed prompt cache. Note, if
          provided, the cache will be updated in place.
        prefill_step_size (int): Step size for processing the prompt.
        kv_bits (int, optional): Number of bits to use for KV cache quantization.
          None implies no cache quantization. Default: ``None``.
        kv_group_size (int): Group size for KV cache quantization. Default: ``64``.
        quantized_kv_start (int): Step to begin using a quantized KV cache.
           when ``kv_bits`` is non-None. Default: ``0``.
        prompt_progress_callback (Callable[[int, int], None]): A call-back which takes the
           prompt tokens processed so far and the total number of prompt tokens.
        input_embeddings (Array, optional): Input embeddings to use instead of or in
          conjunction with prompt tokens. Default: ``None``.

    Yields:
        Tuple[Array, Array]: One token and a vector of log probabilities.
    """
    if len(prompt) == 0:
        raise ValueError(
            "Prompt must be provided."
        )

    tokens = None

    # Create the KV cache for generation
    if prompt_cache is None:
        prompt_cache = ModelCache.cache_for_model(model)

    prompt_progress_callback = prompt_progress_callback or (lambda *_: None)

    # quantize_cache_fn = functools.partial(
    #     maybe_quantize_kv_cache,
    #     quantized_kv_start=quantized_kv_start,
    #     kv_group_size=kv_group_size,
    #     kv_bits=kv_bits,
    # )

    sampler = sampler or default_sampler

    def _step(input_tokens: Array):
        nonlocal tokens

        with ten.stream(generation_stream):
            logits = model(input_tokens[None])

            logits = logits[:, -1, :]

            if logits_processors and len(input_tokens) > 0:
                tokens = (
                    ten.concat([tokens, input_tokens])
                    if tokens is not None
                    else input_tokens
                )
                for processor in logits_processors:
                    logits = processor(tokens, logits)

            # quantize_cache_fn(prompt_cache)

            logprobs = logits - ten.logsumexp(logits, keepdims=True)
            sampled = sampler(logprobs)
            return sampled, logprobs.squeeze(0)

    forward_ctx = model.build_forward_context()
    forward_ctx.cache = prompt_cache

    with forward_ctx.push():
        with ten.stream(generation_stream):
            total_prompt_tokens = len(prompt)
            prompt_processed_tokens = 0
            prompt_progress_callback(prompt_processed_tokens, total_prompt_tokens)
            while total_prompt_tokens - prompt_processed_tokens > 1:
                remaining = (total_prompt_tokens - prompt_processed_tokens) - 1
                n_to_process = min(prefill_step_size, remaining)
                model(prompt[:n_to_process][None])

                ten.eval([c.state for c in prompt_cache])
                prompt_processed_tokens += n_to_process
                prompt_progress_callback(prompt_processed_tokens, total_prompt_tokens)
                prompt = prompt[n_to_process:]
                ten.clear_cache()

            y, logprobs = _step(prompt)

        ten.async_eval(y, logprobs)
        n = 0
        while True:
            if n != max_tokens:
                next_y, next_logprobs = _step(y)
                ten.async_eval(next_y, next_logprobs)
            if n == 0:
                ten.eval(y)
                prompt_progress_callback(total_prompt_tokens, total_prompt_tokens)
            if n == max_tokens:
                break
            yield y.item(), logprobs
            if n % 256 == 0:
                ten.clear_cache()
            y, logprobs = next_y, next_logprobs
            n += 1


def stream_generate(
    model: LanguageModel,
    tokenizer: Tokenizer,
    prompt: Union[str, Array, list[int]],
    max_tokens: int = 256,
    draft_model: Optional[Module] = None,
    **kwargs,
) -> Generator[GenerationResponse, None, None]:
    """
    A generator producing text based on the given prompt from the model.

    Args:
        model (nn.Module): The model to use for generation.
        tokenizer (PreTrainedTokenizer): The tokenizer.
        prompt (Union[str, Array, List[int]]): The input prompt string or
          integer tokens.
        max_tokens (int): The maximum number of tokens to generate.
          Default: ``256``.
        draft_model (Optional[nn.Module]): An optional draft model. If provided
          then speculative decoding is used. The draft model must use the same
          tokenizer as the main model. Default: ``None``.
        kwargs: The remaining options get passed to :func:`generate_step`.
          See :func:`generate_step` for more details.

    Yields:
        GenerationResponse: An instance containing the generated text segment and
            associated metadata. See :class:`GenerationResponse` for details.
    """

    if not isinstance(prompt, Array):
        if isinstance(prompt, str):
            # Try to infer if special tokens are needed
            add_special_tokens = tokenizer.bos_token is None or not prompt.startswith(
                tokenizer.bos_token
            )
            prompt = ten.array(tokenizer.encode(prompt, add_special_tokens=add_special_tokens))
        else:
            prompt = ten.array(prompt)

    detokenizer = tokenizer.detokenizer

    kwargs["max_tokens"] = max_tokens

    if draft_model is None:
        kwargs.pop("num_draft_tokens", None)
        token_generator = generate_step(prompt, model, **kwargs)
        # from_draft always false for non-speculative generation
        token_generator = (
            (token, logprobs, False) for token, logprobs in token_generator
        )
    else:
        kwargs.pop("max_kv_size", None)
        kwargs.pop("prompt_progress_callback", None)
        token_generator = speculative_generate_step(
            prompt, model, draft_model, **kwargs
        )
    with wired_limit(model, [generation_stream]):
        tic = time.perf_counter()
        for n, (token, logprobs, from_draft) in enumerate(token_generator):
            if n == 0:
                prompt_time = time.perf_counter() - tic
                prompt_tps = prompt.size / prompt_time
                tic = time.perf_counter()
            if token in tokenizer.eos_token_ids:
                break

            detokenizer.add_token(token)
            if (n + 1) == max_tokens:
                break

            yield GenerationResponse(
                text=detokenizer.last_segment,
                token=token,
                logprobs=logprobs,
                from_draft=from_draft,
                prompt_tokens=prompt.size,
                prompt_tps=prompt_tps,
                generation_tokens=n + 1,
                generation_tps=(n + 1) / (time.perf_counter() - tic),
                peak_memory=ten.get_peak_memory() / 1e9,
                finish_reason=None,
            )

        detokenizer.finalize()
        yield GenerationResponse(
            text=detokenizer.last_segment,
            token=token,
            logprobs=logprobs,
            from_draft=from_draft,
            prompt_tokens=prompt.size,
            prompt_tps=prompt_tps,
            generation_tokens=n + 1,
            generation_tps=(n + 1) / (time.perf_counter() - tic),
            peak_memory=ten.get_peak_memory() / 1e9,
            finish_reason="stop" if token in tokenizer.eos_token_ids else "length",
        )


def generate(
    model: LanguageModel,
    tokenizer: Tokenizer,
    prompt: Union[str, list[int]],
    verbose: bool = False,
    **kwargs,
) -> str:
    """
    Generate a complete response from the model.

    Args:
       model (nn.Module): The language model.
       tokenizer (PreTrainedTokenizer): The tokenizer.
       prompt (Union[str, List[int]]): The input prompt string or integer tokens.
       verbose (bool): If ``True``, print tokens and timing information.
           Default: ``False``.
       kwargs: The remaining options get passed to :func:`stream_generate`.
          See :func:`stream_generate` for more details.
    """
    if verbose:
        print("=" * 10)

    text = ""
    response = None
    for response in stream_generate(model, tokenizer, prompt, **kwargs):
        if verbose:
            print(response.text, end="", flush=True)
        text += response.text

    if verbose:
        print()
        print("=" * 10)
        if len(text) == 0:
            print("No text generated for this prompt")
            return ''
        if response is not None:
            print(
                f"Prompt: {response.prompt_tokens} tokens, "
                f"{response.prompt_tps:.3f} tokens-per-sec"
            )
            print(
                f"Generation: {response.generation_tokens} tokens, "
                f"{response.generation_tps:.3f} tokens-per-sec"
            )
            print(f"Peak memory: {response.peak_memory:.3f} GB")
    return text
