#  Copyright (c) 2025. Richard Vermillion. All Rights Reserved.
#  Copyright (c) 2025. Richard Vermillion. All Rights Reserved.
import math
from typing import Any, Protocol, TypeGuard
from ..common.core import *

from .types import *

inf = math.inf


class RNG(Protocol):

    def normal(self, loc: ArrayLike = ..., scale: ArrayLike = ..., size: ShapeLike = ...) -> ArrayOrFloat: ...

    def uniform(self, low: ArrayLike = ..., high: ArrayLike = ..., size: ShapeLike = ...) -> ArrayOrFloat: ...

    def exponential(self, rate: ArrayLike = ..., size: ShapeLike = ...) -> ArrayOrFloat: ...


class Random(Protocol):

    Generator: type[RNG]

    @staticmethod
    def default_rng(seed: int = ...) -> RNG: ...

    @staticmethod
    def normal(loc: ArrayLike = ..., scale: ArrayLike = ..., shape: Shape = ..., **kwargs) -> Array: ...

    @staticmethod
    def uniform(low: ArrayLike = ..., high: ArrayLike = ..., shape: Shape = ..., **kwargs) -> Array: ...

    @staticmethod
    def randint(low: ArrayLike = ..., high: ArrayLike = ..., shape: ShapeLike = ..., dtype: DType | None = ...) -> Array: ...

    @staticmethod
    def permutation(size: int, **kwargs) -> Array: ...

    @staticmethod
    def seed(seed: int) -> None: ...


from . import fast, functional, linalg, random

def is_array(obj: Any) -> TypeGuard[Array]: ...

def is_dtype(obj: Any) -> TypeGuard[DType]: ...

def is_rng(obj: Any) -> TypeGuard[RNG]: ...

# noinspection PyShadowingNames
def astype(a: Any, dtype: DType, **kwargs) -> Array: ...

# noinspection PyShadowingNames
def dtype(dtype: DTypeLike) -> DType: ...

# noinspection PyShadowingNames
def array(data, dtype: DTypeLike = ..., *args, **kwargs) -> Array: ...

# noinspection PyShadowingNames
def zeros(shape: Shape, dtype: DTypeLike = ..., *args, **kwargs) -> Array: ...

# noinspection PyShadowingNames
def ones(shape: Shape, dtype: DTypeLike = ..., *args, **kwargs) -> Array: ...

# noinspection PyShadowingNames
def full(shape: Shape, fill_value: Scalar, dtype: DTypeLike = ..., *args, **kwargs) -> Array: ...

# noinspection PyShadowingNames
def zeros_like(array: Array, dtype: DTypeLike = ..., *args, **kwargs) -> Array: ...

def ones_like(array: Array, dtype: DTypeLike = ..., *args, **kwargs) -> Array: ...

def full_like(array: Array, fill_value: Scalar, dtype: DTypeLike = ..., *args, **kwargs) -> Array: ...

def fill(array: Array, fill_value: Scalar, /, **kwargs) -> None: ...

def eye(n: int, m: int = ..., k: int = ..., dtype: DTypeLike = ..., **kwargs) -> Array: ...

def trace(a: Array, /, offset: int = 0, axis1: int = 0, axis2: int = 1, dtype: DTypeLike | None = None, **kwargs) -> Array: ...

def fromfunction(function, shape, *, dtype=float, like=None, **kwargs) -> Array: ...

def arange(start: Scalar, stop: Scalar = ..., step: Scalar = ..., dtype: DType = ...) -> Array: ...

def reshape(a: ArrayLike, shape: Shape, **kwargs) -> Array: ...

def broadcast_to(a: Array, shape: Shape, **kwargs) -> Array: ...

def swapaxes(a: ArrayLike, axis_one: Axis, axis_two: Axis) -> Array: ...

def concatenate(arrays: list[Array], axis: int) -> Array: ...

def any(a: ArrayLike, /, **kwargs) -> bool: ...

def all(a: ArrayLike, /, **kwargs) -> bool: ...

def isinf(a: ArrayLike, /, **kwargs) -> Array: ...

def isnan(a: ArrayLike, /, **kwargs) -> Array: ...

def clip(a: ArrayLike, low: Scalar | None = ..., high: Scalar | None = ..., /, **kwargs) -> Array: ...

# noinspection PyShadowingBuiltins
def abs(a: ArrayLike, /, dtype: DType = ..., **kwargs) -> Array: ...

def floor(a: ArrayLike, /, dtype: DType = ..., **kwargs) -> Array: ...

def square(a: ArrayLike, /, dtype: DType = ..., **kwargs) -> Array: ...

def sqrt(a: ArrayLike, /, dtype: DType = ..., **kwargs) -> Array: ...

def exp(a: ArrayLike, /, dtype: DType = ..., **kwargs) -> Array: ...

def expm1(a: ArrayLike, /, dtype: DType = ..., **kwargs) -> Array: ...

def log(a: ArrayLike, /, dtype: DType = ..., **kwargs) -> Array: ...

def min(a: ArrayLike, axis: Axes = ..., dtype: DType = ..., keepdims: bool = ..., **kwargs) -> Array: ...


# noinspection PyShadowingBuiltins
def max(a: ArrayLike, axis: Axes = ..., dtype: DType = ..., keepdims: bool = ..., **kwargs) -> Array: ...

def sum(a: ArrayLike, axis: Axes = ..., dtype: DType = ..., keepdims: bool = ..., **kwargs) -> Array: ...

def prod(a: ArrayLike, axis: Axes = ..., dtype: DType = ..., keepdims: bool = ..., **kwargs) -> Array: ...

def mean(a: ArrayLike, axis: Axes = ..., dtype: DType = ..., keepdims: bool = ..., **kwargs) -> Array: ...

def std(a: ArrayLike, axis: Axes = ..., dtype: DType = ..., ddof: int = ..., keepdims: bool = ..., **kwargs) -> Array: ...

def var(a: ArrayLike, axis: Axes = ..., dtype: DType = ..., keepdims: bool = ..., **kwargs) -> Array: ...

def median(a: ArrayLike, axis: Axes = ..., dtype: DType = ..., keepdims: bool = ..., **kwargs) -> Array: ...

def softmax(a: ArrayLike, axis: Axes = ..., dtype: DType = ..., keepdims: bool = ..., **kwargs) -> Array: ...

def logsumexp(a: ArrayLike, axis: Axes = ..., dtype: DType = ..., keepdims: bool = ..., **kwargs) -> Array: ...

def argmin(a: ArrayLike, axis: Axes = ..., dtype: DType = ..., keepdims: bool = ..., **kwargs) -> Array: ...

def argmax(a: ArrayLike, axis: Axes = ..., dtype: DType = ..., keepdims: bool = ..., **kwargs) -> Array: ...

def cumsum(a: ArrayLike, axis: Axes = ..., dtype: DType = ..., **kwargs) -> Array: ...

def cummin(a: ArrayLike, axis: Axes = ..., dtype: DType = ..., keepdims: bool = ..., **kwargs) -> Array: ...

def cummax(a: ArrayLike, axis: Axes = ..., dtype: DType = ..., keepdims: bool = ..., **kwargs) -> Array: ...

def cumprod(a: ArrayLike, axis: Axes = ..., dtype: DType = ..., keepdims: bool = ..., **kwargs) -> Array: ...

def broadcast_shapes(a: ArrayLike, b: ArrayLike, /, **kwargs) -> Shape: ...

def array_equal(a: ArrayLike, b: ArrayLike, /, **kwargs) -> bool: ...

def logical_and(a: ArrayLike, b: ArrayLike, /, **kwargs) -> Array: ...

def logical_or(a: ArrayLike, b: ArrayLike, /, **kwargs) -> Array: ...

def matmul(a: ArrayLike, b: ArrayLike, **kwargs) -> Array: ...

def minimum(a: ArrayLike, b: ArrayLike, **kwargs) -> Array: ...

def maximum(a: ArrayLike, b: ArrayLike, **kwargs) -> Array: ...

def clip(a: ArrayLike, a_min: ArrayLike, a_max: ArrayLike, **kwargs) -> Array: ...

def where(a: ArrayLike, b: ArrayLike, c: ArrayLike, **kwargs) -> Array: ...

def is_increasing(a: ArrayLike, strict: bool = ..., **kwargs) -> bool: ...

def is_decreasing(vals: Array, strict: bool = False) -> bool: ...

def is_monotonic(vals: Array, strict: bool = False) -> bool: ...

def average(a: ArrayLike, axis: Axes = ..., weights: ArrayLike = ..., **kwargs) -> Array: ...

def floor_divide(a: ArrayLike, b: ArrayLike, dtype: DTypeLike = ..., **kwargs) -> Array: ...

def sort(a: ArrayLike, axis: Axis = ..., **kwargs) -> Array: ...

def searchsorted(a: ArrayLike, x: ArrayOrScalar, side: str = ...) -> Array: ...

def update(a: Array, where: Array, x: ArrayOrScalar) -> None: ...

def eval(*args: Any) -> None: ...

def debug_eval(*args: Any) -> None: ...

def expand_dims(a: Array, axis: Axes = ...) -> Array: ...

def squeeze(a: Array, axis: Axes = ...) -> Array: ...

def allclose(a: Array, b: Array, /, rtol: float = ..., atol: float = ..., *, equal_nan: bool = False, **kwargs) -> Array: ...

def argsort(a: Array, /, axis: Axes = ..., **kwargs) -> Array: ...

def save_safetensors(file: str, arrays: dict[str, Array], metadata: Any | None = None) -> None: ...

def stack(arrays: list[Array], axis: Any = 0, **kwargs) -> Array: ...

def addmm(c: Array, a: Array, b: Array, /, alpha: float = 1.0, beta: float = 1.0, **kwargs) -> Array: ...

def equal(a: Array, b: ArrayLike, **kwargs) -> Array: ...

def load(file: str, /, format: Any | None = None, return_metadata: bool = False, **kwargs) -> Any: ...

def save(file: str, arr: Array) -> None: ...

def is_integer(dtype: DType) -> bool: ...

def is_floating(dtype: DType) -> bool: ...

# noinspection PyShadowingNames
def select(a: Array, *, where: Array = ...) -> Array: ...

def set_printoptions(**kwargs) -> None: ...

bool_: DType

ten_kind: str


__all__ = [
    'Array',
    'ArrayLike',
    'ArrayOrScalar',
    'Axes',
    'Axis',
    'AxisSelector',
    'DType',
    'DTypeLike',
    'Random',
    'RNG',
    'Scalar',
    'Selector',
    'Shape',
    'ShapeLike',
    # 'Shim',
]