#  Copyright (c) 2025. Richard Vermillion. All Rights Reserved.
from .types import Array, ArrayLike, DType, ShapeLike

def normal(loc: ArrayLike = 0.0, scale: ArrayLike = 1.0, shape: ShapeLike = ...) -> Array: ...

def uniform(low: ArrayLike = ..., high: ArrayLike = ..., shape: ShapeLike = ...) -> Array: ...

def randint(low: ArrayLike = ..., high: ArrayLike = ..., shape: ShapeLike = ..., dtype: DType | None = ...) -> Array: ...

def permutation(size: int, **kwargs) -> Array: ...

def seed(seed: int) -> None: ...
